### ISSUE TITLE
Change from PCRE to POSIX RE

### ISSUE THREAD

**Issue by marvink87** [hSaria/ChromaTerm--#23]
Hi,

Sorry if this is not the place to ask but I have a question.

I'm interested in this fork as I only use the highlighting feature of Chromaterm and this fork promises a major performance increase.  I was just wondering why the REGEX library was changed from PCRE to POSIX? Does this have a huge impact on performance? In the POSIX library I miss features like readahead, lookback and word boundaries.

I say this as a user of the following configuration (not made by me): https://gist.github.com/vista-/7882bc223e3bb209664103fd4736ab7f

**Comment by hSaria** [comment]
Hey @marvink87,

Short version: I'll go ahead and bring back PCRE, most likely.

Long version: read below.

Well, the improvement in performance actually came from how I changed the implementation. The reason I changed to regex.h is because it is a POSIX standard. It makes it easier for people to use.

With that said, I did notice how POSIX misses a few features that other libraries have. I'll go back to PCRE and run some benchmarks (`time cat /path/to/long/file`). Again, since my improvements are due to a change in the implementation, I don't expect any performance hits when going back to PCRE.

**Comment by hSaria** [comment]
@marvink87, you'll be happy to know that I've switched to PCRE. Overall, there's no performance hit when compared to POSIX (well, around 2%, but that's not that significant).

Just a note about the link you provided: It uses the old CT convention for Regex, which required two sets of curly brackets for the contents to be considered as Regex.
In CT--, I've removed the need for double brackets; anything inside the first set of curly brackets is directly passed to the regex engine. You'll have to adjust the file you linked. All you have to do is a quick find and replace:
- `{{` with `{`
-  `}}` with `}`
