### ISSUE TITLE
Prompt not correctly displayed

### ISSUE THREAD

**Issue by marvink87** [hSaria/ChromaTerm--#35]
**Describe the bug**
I noticed the switch to PCRE2 and wanted to try out the performance increase that comes with it. But sadly it doesn't work correctly. My prompt doesn't completely appear and when logged in to routers using tab completion causes it to eat the last character of the word.

The ct binary I build around 2 weeks ago doesn't have this issue. It was build somewhere after changing to PCRE, help displays v0.05

**Screenshots**
This happens if I open CT and just press enter a few times:
> [me@v-server ~]$ ./git/ChromaTerm--/src/ct
> [me@v-server ~]$ 
> [me@v-server ~
> [me@v-server ~

**Environment (please complete the following information):**
 - OS: centos 7
 - Version 7.5.1804 (Core)

**Additional context**
I tried to check if this bug is still present in the development branch but there seem to be some major changes in how CT-- is used there. I couldn't get CT-- working |(prompt was displayed but any command used doesn't display output) but your'e probably still working on that.

**Comment by hSaria** [comment]
@marvink87 

I'll try to recreate the issue on my end. 

- Could you share your .chromatermrc file please?
- Put `%config {HIGHLIGHT} {OFF}` in your .chromatermrc file, and check to see if the issue still exists. (Remove this line once you're done with this test.)
- Could you put `%config {CONVERT META} {ON}` in your .chromatermrc file, recreate the issue, then send that output of your terminal (it'll have some escaped codes that will help me eliminate some of the possible causes). (Remove this line once you're done with this test.)



And you're right, the development branch is something slightly different. That one reads from a pipe (stdin) instead of spawning a child process. In other words, it's like GREP or SED, so the development would be `ssh some_router | ct` 
For now, don't use the development branch because it doesn't have an interactive CT-- prompt (once the program started, you cannot modify the settings). If you're okay with that, then you can go ahead and use it since it's even more stable than v0.1.0.

**Comment by hSaria** [comment]
Just saw the bug when auto-completing. I'll fix it ASAP.

**Comment by hSaria** [comment]
The bug isn't present in the development branch, but again, that doesn't have the interactive CT-- prompt.

**Comment by marvink87** [comment]
No difference when changing highlight to OFF
When setting convert meta to off the output looks like this:
> [kuurstra@v-netjump001 ~]$ ./git/ChromaTerm--/src/ct
> [kuurstra@v-netjump001 ~]$ \r\r
> [kuurstra@v-netjump001 \r\r
> [kuurstra@v-netjump001 \r\r

This is my config: https://gist.github.com/marvink87/1405cc9193091b3da99e70de52544c62
Already tested the config by commenting out all the HIGHLIGHT rules

**Comment by marvink87** [comment]
Logged into a few different devices and everything seems to be working again. 👍

**Comment by hSaria** [comment]
Great. I'll soon release this as v0.1.1

**Comment by hSaria** [comment]
v0.1.1 released; you can go back to the master branch. Thanks a lot for submitting this issue.
