### ISSUE TITLE
Plans to expand functionality?

### ISSUE THREAD

**Issue by cpriest** [hSaria/ChromaTerm--#57]
Are there any plans to further expand on this tool?

I'd love to be able to highlight different parts of a match differently.

Example use case:
192.168.1.0/24

<0f0>192.168.1.0<555>/<aaa>24

IE: IP in green, / in dark grey, CIDR in lighter grey

**Comment by hSaria** [comment]
Sounds good. I'll work on this and release it in v0.4.0 soon.

Originally, this feature was there, but I removed it in favor of keeping things simple and the fact that positive/negative lookbehinds/lookaheads were able to somewhat achieve this functionality, albeit with some limitation from the RegEx engine (e.g. lookbehinds in PCRE couldn't use quantifiers). But it would be more flexible and not too complex to give access to the groups.

**Comment by cpriest** [comment]
I'm not sure how its implemented exactly, but if the highlights could be used in such a way as substitution (in my mind, seems a minor step away from the above), that would be really amazing.

This would be a different use case, say for a docker build line, I've always wished I could insert a newline just before each ^Step \d+/\d+\s+\w+\s+.+$

Such that the line would be colored (with a new line inserted before), I would expect the replacement pattern to be something like:

`\n<fff><00F>$0\n`

I love the simplicity of ChromaTerm, if you're interested I could whip up a .spec file for it, I had compiled/installed it manually but I like it enough I'm going to package it up for my own repo.

**Comment by hSaria** [comment]
Firstly, thank you so much for creating the feature requests. I'll definitely be working on them.

Regarding substitutions, it's a good idea. This was already there in the original ChromaTerm, but I favor simplicity and avoid reinventing the wheel. In fact, I was going to suggest to you using existing tools, like `sed`, but the more I think about it, the more I realise there's a place for substitutions in ChromaTerm--. The main reason for my change of mind on this subject is related one of the things that makes ChromaTerm-- stand out; it works with interactive application (e.g. `ssh`) instead of line-buffering like most other tools. As far as I know, many tools, including `sed`, will line-buffer so that wouldn't solve your problem. I've created #63 for substitutions, but I'll be focussing on more pressing issues, like the config format.

Regarding the spec file, I've created #62 for this. You've already done me a great service with your awesome suggestions, so don't feel like you have to write the spec file. I'll write a spec file if it's not there; you can just sit and relax if you'd like :)

I've created #64 for granting access to capturing groups as part of the action. That'll be a part of v0.4.0. I'll close off this ticket but we can still discuss any other ideas you may have here. If you have more feature requests that fit in the scope of this project, I'd more than happy to consider them and possibly put them in ChromaTerm--.

**Comment by cpriest** [comment]
Sounds great, I was drawn to the simplicity of it.  I've looked around a long time for something basic like this but with a few more tweaks it could really be an awesome general purpose colorizer!
